apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
spec:
  containers:
  - command:
    - /etcd
    - -name
    - etcd0
    - -initial-advertise-peer-urls
    - https://etcd0:2380
    - -listen-peer-urls
    - https://0.0.0.0:2380
    - -listen-client-urls
    - https://0.0.0.0:2379
    - -advertise-client-urls
    - https://etcd0:2379
    - -initial-cluster
    - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
    - -initial-cluster-state
    - new
    - -ca-file=/etc/etcd/client-ca/ca.crt
    - -cert-file=/etc/etcd/client-key/my.crt
    - -key-file=/etc/etcd/client-key/my.key
    - -peer-ca-file=/etc/etcd/peer-ca/ca.crt
    - -peer-cert-file=/etc/etcd/peer-key/my.crt
    - -peer-key-file=/etc/etcd/peer-key/my.key
    image: quay.io/coreos/etcd:latest
    name: etcd0
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/etcd/peer-ca/
      name: peer-ca
      readOnly: True
    - mountPath: /etc/etcd/client-ca/
      name: client-ca
      readOnly: True
    - mountPath: /etc/etcd/peer-key/
      name: peer-key
      readOnly: True
    - mountPath: /etc/etcd/client-key/
      name: client-key
      readOnly: True
  restartPolicy: Never
  volumes:
  - secret:
      secretName: etcd-peer-ca
    name: peer-ca
  - secret:
      secretName: etcd0-peer-key
    name: peer-key
  - secret:
      secretName: etcd-client-ca
    name: client-ca
  - secret:
      secretName: etcd0-client-key
    name: client-key

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd1
  name: etcd1
spec:
  containers:
  - command:
    - /etcd
    - -name
    - etcd1
    - -initial-advertise-peer-urls
    - https://etcd1:2380
    - -listen-peer-urls
    - https://0.0.0.0:2380
    - -listen-client-urls
    - https://0.0.0.0:2379
    - -advertise-client-urls
    - https://etcd1:2379
    - -initial-cluster
    - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
    - -initial-cluster-state
    - new
    - -ca-file=/etc/etcd/client-ca/ca.crt
    - -cert-file=/etc/etcd/client-key/my.crt
    - -key-file=/etc/etcd/client-key/my.key
    - -peer-ca-file=/etc/etcd/peer-ca/ca.crt
    - -peer-cert-file=/etc/etcd/peer-key/my.crt
    - -peer-key-file=/etc/etcd/peer-key/my.key
    image: quay.io/coreos/etcd:latest
    name: etcd1
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/etcd/peer-ca/
      name: peer-ca
      readOnly: True
    - mountPath: /etc/etcd/client-ca/
      name: client-ca
      readOnly: True
    - mountPath: /etc/etcd/peer-key/
      name: peer-key
      readOnly: True
    - mountPath: /etc/etcd/client-key/
      name: client-key
      readOnly: True
  restartPolicy: Never
  volumes:
  - secret:
      secretName: etcd-peer-ca
    name: peer-ca
  - secret:
      secretName: etcd1-peer-key
    name: peer-key
  - secret:
      secretName: etcd-client-ca
    name: client-ca
  - secret:
      secretName: etcd1-client-key
    name: client-key

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd1
  name: etcd1
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd1

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd2
  name: etcd2
spec:
  containers:
  - command:
    - /etcd
    - -name
    - etcd2
    - -initial-advertise-peer-urls
    - https://etcd2:2380
    - -listen-peer-urls
    - https://0.0.0.0:2380
    - -listen-client-urls
    - https://0.0.0.0:2379
    - -advertise-client-urls
    - https://etcd2:2379
    - -initial-cluster
    - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
    - -initial-cluster-state
    - new
    - -ca-file=/etc/etcd/client-ca/ca.crt
    - -cert-file=/etc/etcd/client-key/my.crt
    - -key-file=/etc/etcd/client-key/my.key
    - -peer-ca-file=/etc/etcd/peer-ca/ca.crt
    - -peer-cert-file=/etc/etcd/peer-key/my.crt
    - -peer-key-file=/etc/etcd/peer-key/my.key
    image: quay.io/coreos/etcd:latest
    name: etcd2
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/etcd/peer-ca/
      name: peer-ca
      readOnly: True
    - mountPath: /etc/etcd/client-ca/
      name: client-ca
      readOnly: True
    - mountPath: /etc/etcd/peer-key/
      name: peer-key
      readOnly: True
    - mountPath: /etc/etcd/client-key/
      name: client-key
      readOnly: True
  restartPolicy: Never
  volumes:
  - secret:
      secretName: etcd-peer-ca
    name: peer-ca
  - secret:
      secretName: etcd2-peer-key
    name: peer-key
  - secret:
      secretName: etcd-client-ca
    name: client-ca
  - secret:
      secretName: etcd2-client-key
    name: client-key

---

apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd2
  name: etcd2
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd2
