kind: Service
apiVersion: v1
metadata: 
  name: etcd-client
spec:
  selector:
    service: etcd
  ports:
  - port: 2380
    targetPort: 2380
    protocol: TCP
    name: peer
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: client
